### ISSUE TITLE
Track user on every survey page?

### ISSUE THREAD

**Issue by SteveCohen** [SteveCohen/Piwik-for-Limesurvey#1]
This plugin will track users on EVERY survey page. Is this desirable?

I imagine that tracking every page would be useful, as Piwik would then track the total time taken in the survey, and we could eventually use Piwik's event and content tracking to log special events (e.g. completed survey, questions that were viewed but not answered - see placeholders in the code).  

Thoughts?

**Comment by Shnoulle** [comment]
Core GA track only survey page, this one is better. I think we have to track all public page. I dislike to have the option to track admin page ... 
Maybe : 

1. remove the system to track admin page: set to 0 always
2. Add a setting : don't track admin. If user is loggued as admin : remove the tracking system.

**Comment by SteveCohen** [comment]
I would like to continue having the option to track admin pages: this is actually why I was interested in the plugin in the first place! 
I wanted to monitor how long users (e.g. staff, clients, etc) spent developing their surveys. I also have a UX background and would like to use this information to improve the core LS interface (one day).  I do agree not everyone wants that, so it should *default* to 0.  However it doesn't need to be the very first option on the settings page. So, another option:

3.move to the bottom of that page, possibly under a separate heading

**Comment by Shnoulle** [comment]
OK, then close the 1st problem :) . I set it default to no , OK for you ?

For the setting : i add it in a future pull request :)

**Comment by Shnoulle** [comment]
PS: did the "use public settings for URL" is OK with your admin tracking page ?

**Comment by SteveCohen** [comment]
Default=No is good for me.

What do you mean by "public settings for URL"?

**Comment by Shnoulle** [comment]
https://github.com/SteveCohen/Piwik-for-Limesurvey/blob/master/PiwikPlugin/PiwikPlugin.php#L71 :)

**Comment by SteveCohen** [comment]
Yes, that works for the admin pages still. Thanks for asking :)

Question: piwik_rewriteURLs can be set to  'Admin' or  'Public' but not both.  What if a user wants to rewrite admin AND public? Or do I misunderstand?

**Comment by Shnoulle** [comment]
Then : 
* Tracking admin page is OK with settings "False url" and "Public URL"
* I think if we use "Use admin page" in the settings : there are no difference between admin and public page. But user have another choice
* I still have an issue with my config ('showScriptName' => false,) i have surveyid wothout sid before. But using false url fix the issue (i search for a better method).

You want a settings : "Track only admin page" ? Or maube netter : track only "welcome page" ?

**Comment by Shnoulle** [comment]
Think this one can be closed ? We track every survey age (even preview if admin loguing is active)
