### ISSUE TITLE
Did we want to track this params

### ISSUE THREAD

**Issue by Shnoulle** [SteveCohen/Piwik-for-Limesurvey#11]
Did we want to track
- User language
- User action (move next/move previous etc...)

Maybe option for activate this tracks ? Only track sid/gid/qid/save/load/register/token by default ?

**Comment by SteveCohen** [comment]
Language: Yes, it can't hurt! :) Of course this would be included in the limesurvey dataset.

User actions: Next/back/load/save user actions are tracked under the 'event tracking' (In Piwik, shown under Visitors->Events), but I'm not sure how they appear in the URLs view.  If you want to see the Piwik-For-Limesurvey code code, do a search for the variable 'piwik_trackEvents'.

Another thing to track:
* LS Respondent ID number should be added to Piwik to allow admins to find specific respondents in Piwik.

**Comment by Shnoulle** [comment]
In the last version, i add an "event" and "action" to the url.
See : https://github.com/SteveCohen/Piwik-for-Limesurvey/commit/7657dd489d4de23855455d17e6c4c180f7998fa6#diff-e71d6e79401af7b5003bbf32b371fea8R350

And adding the getMove from LS to "action" : https://github.com/SteveCohen/Piwik-for-Limesurvey/commit/7657dd489d4de23855455d17e6c4c180f7998fa6#diff-e71d6e79401af7b5003bbf32b371fea8R467
Then i think we have movenext/movesubmit etc ...

(tested in some condition)

**Comment by SteveCohen** [comment]
ok, I'll have to look more closely at that. Todo this weekend. :)

**Comment by SteveCohen** [comment]
I think this should be closed?

**Comment by Shnoulle** [comment]
yes
