### ISSUE TITLE
LimeSurvey 2.06 Build 150825 : Survey listing is untracked

### ISSUE THREAD

**Issue by Shnoulle** [SteveCohen/Piwik-for-Limesurvey#14]
To track "all page" by default : we use afterPluginLoad.

But after last update : seems afterPluginLoad is not called for Survey list page. Survey page seems OK (start/group/restart, not tested : save/register). @Todo: test the admin page.

**Comment by Shnoulle** [comment]
When you start updating plugin for 2.50 (or 2.06_SondagesPro) : we can fix it.

**Comment by SteveCohen** [comment]
Hi Denis, thanks for the reminder. I haven't been focusing on Piwik for Limesurvey but do intend to get back to it. Will linstall  a copy of 2.50 soon. Steve.

**Comment by Shnoulle** [comment]
Hi @SteveCohen : : i start it, no problem. ,But make a new branch :).

Then when it's ready, i send you the new branch, because we can not have 2.06 + 2.50 compatibility :cry:

**Comment by Shnoulle** [comment]
2.06 is deprecated .
