### ISSUE TITLE
Class 'string' not found

### ISSUE THREAD

**Issue by trockenasche** [SteveCohen/Piwik-for-Limesurvey#20]
I downloaded the PiwikPlugin.php and copy it to the Pluginfolder/PiwikPlugin.
LimeSurvey plugin manager list the plugin and I can configureting evrything.
But when I click save I get a http 500 error with the message `Class 'string' not found`.

LimeSurvey Version 2.72.0+171010

**Comment by Shnoulle** [comment]
Hi,

There are a bug in 2.72.0, must update to 2.72.1 : https://github.com/LimeSurvey/LimeSurvey/commit/e52da872d648f16a8dd298da4169231e37972412

**Comment by trockenasche** [comment]
Thanks, this worked!
