### ISSUE TITLE
Fatal error: Declaration of PiwikPlugin::__construct

### ISSUE THREAD

**Issue by umpire274** [SteveCohen/Piwik-for-Limesurvey#23]
Hi Steve.
I've tried to install you plugin on my Limesurvey installation, but when I visited the Plugin Manager I obtain this fatal error:

`Fatal error: Declaration of PiwikPlugin::__construct(LimeSurvey\PluginManager\PluginManager $manager, $id) must be compatible with ls\pluginmanager\iPlugin::__construct(PluginManager $manager, $id) in /xxxx/xxxx/usr/local/nginx/html/LimeSurvey-2.73.1-171220/plugins/PiwikPlugin/PiwikPlugin.php on line 26`

Can you help me?

My server is configured like this.

SO: CentOS 6.10 Final
Web Server: Nginx 1.15.5
PHP: 7.0.32
Limesurvey: 2.73.1-171220

Alex.

**Comment by SteveCohen** [comment]
Hi Alex, 
I haven't seen that error before, but judging by [this](https://www.limesurvey.org/forum/french-forum/113357-probleme-maj-version-3-0-1-avec-plugin-cas) post by @Shnoulle, it's probably happening becuase you are using LS v2.73. We made a minor changes in the last PR to enable Limesurvey V3, which uses a different plugin API.

So, the quickest solution here is probably...
- upgrade limesurvey to v3.x
- try version of the plugin compatible with LS 2.x (e.g. [this version](https://github.com/SteveCohen/Piwik-for-Limesurvey/commit/7505d2c629a0ed4992e7eece6b1f8a21fc05b706))

**Comment by umpire274** [comment]
Hi Steve.

Yes, your suggestion is right. I used the version for LS 2.x and the error gone.

I can suggest to create a branch for this version (LS 2.x)?

Thanks,
Alex.
