### ISSUE TITLE
Hard to use git in plugins

### ISSUE THREAD

**Issue by Shnoulle** [SteveCohen/Piwik-for-Limesurvey#4]
Have the plugin in a subdirectory make harder to use directly git pull.

Instruction can be:

     git clone https://github.com/SteveCohen/Piwik-for-Limesurvey.git PiwikPlugin

or 

    wget https://github.com/SteveCohen/Piwik-for-Limesurvey/archive/master.zip
    unzip Piwik-for-Limesurvey-master.zip
    mv Piwik-for-Limesurvey PiwikPlugin

**Comment by SteveCohen** [comment]
Hm. Yes, I agree. I'll update the installation instructions.
