### ISSUE TITLE
URL tracking format

### ISSUE THREAD

**Issue by SteveCohen** [SteveCohen/Piwik-for-Limesurvey#5]
@Shnoulle, I'm currently updating the URL tracking code; could you tell me why you added survey' in two spots in urls? e.g. 
```
$piwikCustomUrl="survey/".$iSurveyId."/survey";
```
This generates a heirarchy in piwik like this (note that survey/survey is visible)
![Double 'survey' visible](https://cloud.githubusercontent.com/assets/5635657/6196350/d9df112e-b42b-11e4-9e97-86889edf716b.png)

Did you choose that for a reason? Othewise I'll reduce to things like:
```
$piwikCustomUrl=$iSurveyId."/survey";
```

**Comment by Shnoulle** [comment]
Oups, we have to review this ....

I want more something like this

* survey
  * 10000
    * completed
    * group
      * 20
      * 21
      * 22
    * new
    * survey
* surveys
  * list

But your rigth : defaut must be just index (when we don't actually know the page).

**Comment by SteveCohen** [comment]
I agree what you wanted is much better :) The customURLs are showing in mine, at least after [this last commit](https://github.com/SteveCohen/Piwik-for-Limesurvey/commit/b0728abcf23cb38fba7c4dbffba7f4f99ffde630). This also has an option to enable/disable url rewriting. Could you confirm they don't work for you?

I think it is useful to track the pages separately from events. Here are my thoughts:

- **Pages** (i.e. using setCustomURL) should track every GET request sent to limesurvey. This allows admins to work out which pages respondents go to. (I don't think this is very useful becuase it doesn't tell you much about your survey, but it is an important basic feature).

Two things can then be tracked on each individual page: 
- **Event tracking** is used for main events, like save/clear/previous (and maybe next) buttons, and completing the survey. These are relatively rare events and allow admins to identify special/weird things happening.
- **Content diplay and interactions** are about questions e.g. viewing the question, selecting a radio button, changing it, etc.

If each of these types of tracking (Pages, Event and Content) can be turned on and off individually, then admins can collect only the data they want and nothing more. What do you think?

**Comment by Shnoulle** [comment]
The Pages is really tricky, because all page of survey expect firt are survey/index.php ( survey/sid/77676 with 2.06) then we don't really need real page.
But actual solution for customUrl don't seem to work with my piwik ? 

For different path/view : i look more.

**Comment by Shnoulle** [comment]
Did new format is better ? admin and public way ? And false way too ?

**Comment by SteveCohen** [comment]
Hmm.. piwik_rewriteURLs can be set to  'Admin' or  'Public' but not both.  What if a user wants to rewrite admin AND public? Or do I misunderstand? Could you give me some examples of what you intended?

**Comment by Shnoulle** [comment]
Hi Steve,

It's rewriting only the public survey url. Not for admin part.

exemple for group id ID
Using public : surveyid/XXXX/group/ID ....
Using admin : /admin/index/view/survey/XXXX/group/ID (same than the admin url to view this group).

I don't want to rewrite admin part. maybe i made error here ?
Denis

**Comment by SteveCohen** [comment]
AAhh... Okay. I understand. I agree 'Public' and 'unreal' and i think these are useful. 

If I understand 'admin' correctly (i.e. when a user visits the first page of the survey it will register the corresponding admin page in Piwik), that is not a feature I expected, and it confused me. Do we need this? What use case would this be used in? 

My thoughts:
* Who would use this? Setting to 'admin' could help survey owners edit their survey... but LS won't allow editing once a survey is live. So this setting is only useful for test surveys anyway. 
* Why would they use it? What data would a tester need from Piwik that they don't already know?
* How to differentiate from other similar options? This would get confusing to have the piwik_rewriteURLs='admin' and piwik_trackAdminPages='yes', because each would generate the same urls. 
If the setting is kept, we will need to explain these things in the interface somewhere (which is due for a tidy up anyway).

Unless I have something wrong, I suggest removing the 'admin' option for piwik_rewriteURLs. What do you think?

**Comment by Shnoulle** [comment]
Who use it : case:
* Set "track admin" to NO
* Set "url to admin" to YES
=> Url shown in Piwik link to admin poage directly , with /surveyid/XXXX/gid/XXXX 

I think it's really a great url system, i use false, but i think i rework on it too.

**Comment by SteveCohen** [comment]
Ok, happy to keep it :)
I think we will need to work on the settings page interface though:
![screen shot 2015-04-13 at 8 22 55 am](https://cloud.githubusercontent.com/assets/5635657/7107853/4f47d556-e1b6-11e4-9015-d2483f710840.png) 
...I think the first item ("No" in this case) determines the width of the subsequent ones. Maybe put 'yes....' first but leave the default the same?

**Comment by Shnoulle** [comment]
LS core bug, for survey seeting part : can add a "surveysetting_fix.css".

Denis

**Comment by Shnoulle** [comment]
Can be closed ?
