### ISSUE TITLE
Publish Plugin on Piwik and LimeSurvey.org

### ISSUE THREAD

**Issue by Shnoulle** [SteveCohen/Piwik-for-Limesurvey#6]
@SteveCohen 

Hi,

Sending a mail to Matthieu Aubry, founder and core devlopper of piwik

> Sujet : 	Re: [piwik.org/contact] New message to the Piwik team
> Date : 	Sat, 07 Feb 2015 12:40:30 +1300
> De : 	Matthieu Aubry 
> Pour : 	Denis Chenu 
> 
> Hi Denis,
> 
> That's really great news about the plugin :-) I really love Limesurvey and so happy to see it. we will use it ourselves on the next survey :-)
> 
> As soon as it's ready as beta, please let me know, and send me a short description, limesurvey logo, i'll add it to  http://piwik.org/integrate
> 
> is there a place on limesurvey where you could maybe also advertise the plugin, such as their forums?
> also feel free to post a note on the piwik forum for example http://forum.piwik.org/list.php?15
> 
> 
> Cheers,
> 
> Matthieu
> Piwik founder

I let you decide when it's in Beta :)

PS: i think we must start by https://www.limesurvey.org/en/extensions ?

**Comment by SteveCohen** [comment]
Thank you for reaching out to Mattieu, Denis. I emailed the Piwik team a few days ago too, and they have added a link on http://piwik.org/integrate yesterday. As they say: "Great minds think alike!". 

However, I don't think it's "Beta" yet. I will work hard to get it there soon :) Adding to https://www.limesurvey.org/en/extensions is a great idea. Maybe that should wait until it is actually Beta? Or just add it now?

**Comment by Shnoulle** [comment]
You'r rigth, beta wait :)

**Comment by SteveCohen** [comment]
Haha. We Beta wait. Well said :)

**Comment by Shnoulle** [comment]
@SteveCohen : maybe we can have some direct contact too ... IRC or email ? (i think you can have my email easili, else search shnoulle or sondages.pro at https://duckduckgo.com
