### ISSUE TITLE
Move customurl in head

### ISSUE THREAD

**Issue by Shnoulle** [SteveCohen/Piwik-for-Limesurvey#7]
Looking at code,

We do:

```javascript
/*<![CDATA[*/
var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u='//piwik.exemple.net/';
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 8]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
_paq.push(['setCustomUrl', 'surveys'])
/*]]>*/
```

Maybe it's better to set like this

head (or start of body)
```javascript
piwikLimeSurvey={"customUrl":"surveys"}
```

And at end of body:
```javascript
/*<![CDATA[*/
var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u='//piwik.example.net/';
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 8]);
    _paq.push(['setCustomUrl', piwikLimeSurvey.customUrl])
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
/*]]>*/
```

Don't know ? Then user can update the cutomUrl in the survey :) (or in template)

**Comment by SteveCohen** [comment]
Agreed. Great suggestion! It's great that this will allow other templates/etc to update the URL as needed.

I'm working on URL rewriting today so I'll include this in my next update.

**Comment by SteveCohen** [comment]
Added to [latest commit](https://github.com/SteveCohen/Piwik-for-Limesurvey/commit/b0728abcf23cb38fba7c4dbffba7f4f99ffde630).  This is pretty basic: 
```
piwikForLimeSurvey={'setCustomUrl':'$piwikCustomUrl'}
```
But piwikForLimeSurvey should be initialised properly to allow other vars to be added later. e.g. in afterpluginload, doing **piwikForLimeSurvey={}** and then any time later, doing **piwikForLimeSurvey['setCustomURL']='example.com';**

This would let us easily set other urls too, without the current code overwriting them. 

I/we should do this when it's needed :)

**Comment by Shnoulle** [comment]
And why not in 

       "piwikForLimeSurvey={'setCustomUrl':'".App()->getUrlManager()->parseUrl(App()->getRequest())."'}

?

Let e have a look wth different system (path/get .... etc)

**Comment by Shnoulle** [comment]
And why not:

head or body start : 
```javascript
var _paq ;
    _paq.push(['setCustomUrl', piwikForLimeSurvey.setCustomUrl]);
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    // Other setting by plugin
```

End:
```javascript
(function() {
    var u='//piwik.example.net/';
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 8]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
})();
```

Maybe it's more easy to dev like this ?

**Comment by SteveCohen** [comment]
Hmm.. initialising _paq in the head is good. I wish I thought of that yesterday! :/

**Comment by Shnoulle** [comment]
Yes, so am i ..... But actual solution just need var _paq = _paq || []; at head.....

And with actual 'customUrl' the url allways go to a 404 in piwik management. Your rigth : maybe the url mus go to a real url (but some can not be the good).

The best : url link : goes to admin page BUT shown like survey/XXX/group/XXX ....

Hard to find the best way.

**Comment by Shnoulle** [comment]
Done in https://github.com/SteveCohen/Piwik-for-Limesurvey/pull/10#discussion_r26118555
